resource_group_name = "ado-aks-dev-rg"
location = "southindia"
service_principal_name = "ado-aks-dev-sp"
key_vault_name = "ado-aks-dev-kv"
sub_id = "f28577aa-ecad-4b8d-a9b7-ee289e3a749c"
node_pool_name = "devnodepool1"
cluster_name = "ado_aks_dev_cluster"
